site_name: Lyrics Book
site_url: https://doc.jinvic.top/lyrics
repo_url: https://github.com/Jinvic/lyrics
repo_name: Jinvic/lyrics
site_description: some lyrics for self use.
site_author: Jinvic

theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.progress
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share

nav:
  - Home: 'README.md'
  - Catalog: 'catalog.md'
  - カンザキイオリ:
    - 'カンザキイオリ/index.md'
    - 命に嫌われている: 'カンザキイオリ/命に嫌われている.md'
    - あの夏が飽和する: 'カンザキイオリ/あの夏が飽和する.md'
    - 死ぬとき死ねばいい: 'カンザキイオリ/死ぬとき死ねばいい.md'
    - 人生はコメデイ: 'カンザキイオリ/人生はコメデイ.md'
    - 君の神様になりたい: 'カンザキイオリ/君の神様になりたい.md'
    - 自由に捕らわれる: 'カンザキイオリ/自由に捕らわれる.md'
    - 不器用な男: カンザキイオリ/不器用な男.md
    - 少年少女: 'カンザキイオリ/少年少女.md'
    - 愛があれば: 'カンザキイオリ/愛があれば.md'
    - 音楽なんてわからない: 'カンザキイオリ/音楽なんてわからない.md'
    - 進化劇: 'カンザキイオリ/進化劇.md'
    - 地獄に落ちる: 'カンザキイオリ/地獄に落ちる.md'
    - 人間じゃない癖に: 'カンザキイオリ/人間じゃない癖に.md'
  - DECO*27:
    - 'deco27/index.md'
    - 二息步行: 'deco27/二息步行.md'
    - モザイクロール: 'deco27/モザイクロール.md'
    - 妄想税: 'deco27/妄想税.md'
    - ゴーストルール: 'deco27/ゴーストルール.md'
    - ヒバナ: 'deco27\ヒバナ.md'
    - アンドロイドガール: 'deco27\アンドロイドガール.md'
    - アンデッドアリスへ: 'deco27\アンデッドアリスへ.md'

plugins:
  - search:
      lang:
        - zh
        - en
        - jp

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true  # 可选：启用更紧凑样式
